server:
  port: 8080

spring:
  application:
    name: api-gateway


  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: Auth-Service
          uri: http://localhost:8081
          predicates:
            - Path=/Users/**
          filters:
            - ApiKeyValidation
        - id: Auth-Service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
          filters:
            - name: JwtValidation
              args:
                allowedRoles: FARMER, ADMIN
        # - id: restaurant-service
        #   uri: lb://restaurant-service
        #   predicates:
        #     - Path=/restaurants/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
