server:
  port: 8080

spring:
  application:
    name: api-gateway


  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
        - id: RESTORENT-SERVICE
          uri: lb://RESTORENT-SERVICE
          predicates:
            - Path=/restaurants/**
        

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
