spring:
  application:
    name: Restorent-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant_db
    username: root
    password: Pavan@1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        fromat_sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

